### ISSUE TITLE
User without username causes failure

### ISSUE THREAD

**Issue by chrisfarms** [cdelashmutt-pivotal/service-use#2]
We have a user that does not have a username set in uaa.

This causes a panic due to an expectation that there is always a username set:

```
    return OrgManager{
	UserName:           entity["username"].(string),
    }
```

This could be fixed to allow blank usernames by doing something like:

```
    username,_ := entity["username"].(string),
    return OrgManager{
	UserName:  username
    }
```

**Comment by cdelashmutt-pivotal** [comment]
Thanks for the report!
